apiVersion: v1
items:
- apiVersion: v1
  data:
    token: <your_token>  #钉钉token
  kind: Secret
  metadata:
    managedFields:
    name: dingtalk-secret
    namespace: monitoring
  type: Opaque
- apiVersion: v1
  data:
    token: <your_sign> #钉钉加盐
  kind: Secret
  metadata:
    name: dingtalk-sign
    namespace: monitoring
  type: Opaque
kind: List
