apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    argocd.argoproj.io/instance: dingding-hook
    app: dingding-hook
  name: dingding-hook
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      argocd.argoproj.io/instance: dingding-hook
      app: dingding-hook
  template:
    metadata:
      labels:
        argocd.argoproj.io/instance: dingding-hook
        app: dingding-hook
    spec:
      imagePullSecrets:
      - name: harborsecret
      containers:
      - image: harbor.wqsp.com/ops-library/dingding:v1.5
        imagePullPolicy: IfNotPresent
        name: dingding-hook
        env:
        - name: ROBOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: dingtalk-secret
              key: token
        - name: ROBOT_SECRET
          valueFrom:
            secretKeyRef:
              name: dingtalk-sign
              key: token

        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: harborsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seLinuxOptions: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
